### ISSUE TITLE
Clicking New Folder in File Window Acts unexpectedly

### ISSUE THREAD

**Issue by maxoakland** [gingerbeardman/stapler#26]
If you have a question, please use Discussions (link above)

**Describe the bug**
I started Stapler, it opened a File window, I clicked New Folder to make a new folder for the app and it instantly opened a Stapler Window

**To Reproduce**
Try doing what I did

**Expected behavior**
Create a new folder

**Screenshots**

**Versions (please complete the following information):**
 - macOS version Sonoma

**Comment by gingerbeardman** [comment]
There is a "New Document" button in the initial file selector, which as it says will create a new document. Otherwise you are to use the file selector to choose an existing document to open.

If you don't see the same as below, please post a screenshot.

<img width="912" alt="Screen shot 2024-08-20 at 21 46 27" src="https://github.com/user-attachments/assets/b670bb41-0f86-4ec5-8ab3-f9d0ace00ae4">

**Comment by gingerbeardman** [comment]
Closing.

Feel free to reply if there's anything more to add.

**Comment by maxoakland** [comment]
OK yes, I thought that was the new folder button. I'm so used to the New Folder button being in that exact location that I didn't even think twice

Instead of replacing that useful button, why not add a new button?

**Comment by gingerbeardman** [comment]
I don't make any changes to this dialog. 

This is standard behaviour for a Document-Based App.
