### ISSUE TITLE
Support macOS 13 (Ventura) and 12 (Monterey)

### ISSUE THREAD

**Issue by sgwilym** [gingerbeardman/stapler#7]
Downloaded and saw that it requires macOS 14.0 or later. Aw.

**Comment by gingerbeardman** [comment]
I know this feeling so well! For years I was tracking behind and I even skipped Catalina and Ventura completely. Buying an iPad that was on newer brought me to Sonoma.

These are the things it uses from 14
<img width="294" alt="image" src="https://github.com/user-attachments/assets/85e45a51-14a5-499e-a56d-c2fb4bf74a3e">

There may be a way to use older things that exist in Swift/SwiftUI macOS 13, and even 12, but to be honest the whole thing is a clusterfuck and IMHO the worse thing Apple have pushed on developers in decades.

If I do make these changes — which I probably will :) — i'd like to do it in a way that uses `#ifdef` so that if/when I eventually strip out the old code and force newer macOS it will be easy to just remove those. It will also make the code more readable.

**Comment by gingerbeardman** [comment]
This is done in https://github.com/gingerbeardman/stapler/commit/c202c2ee40ab23bfa9a97cdfb773ef0fba4a4213

New build "soon".

**Comment by gingerbeardman** [comment]
Added in 1.2 https://github.com/gingerbeardman/stapler/releases/tag/1.2

**Comment by sgwilym** [comment]
Returning from a break, thank you for this!!!
